Repository maidsafe/safe-app-csharp, pull requests merged in 2019-09, with the labels that each got.

#86 chore/CI: disable doc deployment and coverage report on AppVeyor
  CakeHelperScripts/DesktopTest.cake
  appveyor.yml
Labels: Chore/CI

#87 chore/CI: disable appveyor deploy
  appveyor.yml
Labels: Chore/CI

#83 Removed all tests, except mock-build tests for verifying CI.
  SafeApp.AppBindings/AppBindings.Manual.cs
  SafeApp.AppBindings/AppBindings.cs
  SafeApp/Misc/CipherOpt.cs
  SafeApp/NativeHandle.cs
  SafeApp/Session.cs
  Tests/SafeApp.Tests/AuthTests.cs
  Tests/SafeApp.Tests/CryptoTests.cs
  Tests/SafeApp.Tests/ImmutableDataTests.cs
  Tests/SafeApp.Tests/MiscTest.cs
  Tests/SafeApp.Tests/MutableDataTests.cs
  Tests/SafeApp.Tests/NFS.cs
  Tests/SafeApp.Tests/SafeApp.Tests.projitems
  Tests/SafeApp.Tests/Utils.cs
Labels: Chore/CI, Don't Merge !!!, e/M :clock3:

#100 Remove SCL bindings, API wrapper, data types and update mock auth bindings to the latest
  SafeApp.AppBindings/Abstraction/IAppBindings.Manual.cs
  SafeApp.AppBindings/Abstraction/IAppBindings.cs
  SafeApp.AppBindings/AppBindings.Manual.cs
  SafeApp.AppBindings/AppBindings.cs
  SafeApp.AppBindings/SafeApp.AppBindings.csproj
  SafeApp.Core/AppConstants.cs
  SafeApp.Core/AppTypes.cs
  SafeApp.MockAuthBindings/Abstraction/IAuthBindings.cs
  SafeApp.MockAuthBindings/AuthBindings.cs
  SafeApp.MockAuthBindings/Authenticator.cs
  SafeApp/AccessContainer.cs
  SafeApp/IData/IData.cs
  SafeApp/MData/MData.cs
  SafeApp/MData/MDataEntries.cs
  SafeApp/MData/MDataEntryActions.cs
  SafeApp/MData/MDataInfoActions.cs
  SafeApp/MData/MDataPermissions.cs
  SafeApp/Misc/CipherOpt.cs
  SafeApp/Misc/Crypto.cs
  SafeApp/Misc/NFS.cs
  SafeApp/Session.cs
  build.cake
Labels: e/M :clock3:, p/major
