Repository maidsafe/safe-app-csharp, pull requests merged in 2019-10, with the labels that each got.

#116 Files API and Tests
  SafeApp.AppBindings/Abstraction/IAppBindings.cs
  SafeApp.AppBindings/AppBindings.HighLevel.cs
  SafeApp.Core/AppTypes.HighLevel.cs
  SafeApp/API/Files.cs
  SafeApp/Session.cs
  Tests/SafeApp.Tests/FilesTest.cs
  Tests/SafeApp.Tests/SafeApp.Tests.projitems
Labels: Binding

#117 Rename CakeHelperScripts folder to Build and move cake scripts to Build folder
  Build/AndroidTest.cake
  Build/DesktopTest.cake
  Build/InspectCode.cake
  Build/NativeScriptDownloader.cake
  Build/Utility.cake
  Build/build.cake
  Build/build.ps1
  Build/build.sh
  Build/iOSTest.cake
  Build/tools/packages.config
  appveyor.yml
Labels: p/minor

#120 Include marshalling for XorUrl APIs and update tests
  SafeApp.AppBindings/AppBindings.HighLevel.cs
  Tests/SafeApp.Tests/XorUrlEncoderTest.cs
Labels: e/S :clock12:, p/minor

#124 refactor/api: use readonly app pointer
  SafeApp/API/Fetch.cs
  SafeApp/API/Files.cs
  SafeApp/API/Keys.cs
  SafeApp/API/Wallet.cs
Labels: e/S :clock12:, p/trivial

#132 refactor/bindings: add xorurl field for fetch data types
  SafeApp.Core/AppTypes.HighLevel.cs
  Tests/SafeApp.Tests/FetchTest.cs
  Tests/SafeApp.Tests/NrsTest.cs
  Tests/SafeApp.Tests/XorUrlEncoderTest.cs
Labels: Binding

#134 Add XML documentation for the new API
  SafeApp.Core/AppTypes.HighLevel.cs
  SafeApp.Core/SafeApp.Core.csproj
  SafeApp.Core/Serialization.cs
  SafeApp.MockAuthBindings/SafeApp.MockAuthBindings.csproj
  SafeApp/API/Fetch.cs
  SafeApp/API/Files.cs
  SafeApp/API/Keys.cs
  SafeApp/API/Nrs.cs
  SafeApp/API/Wallet.cs
  SafeApp/API/XorEncoder.cs
  SafeApp/SafeApp.csproj
  SafeApp/Session.cs
Labels: documentation :bookmark_tabs:

#152 refactor/fetchTest: divide the fetch and inspect tests into two
  SafeApp.AppBindings/AppBindings.HighLevel.cs
  Tests/SafeApp.Tests/FetchTest.cs
Labels: p/trivial
