Repository maidsafe/safe-app-csharp, pull requests merged in 2019-08, with the labels that each got.

#72 docs/SafeApp: udpate broken blog link
  README.md
Labels: documentation :bookmark_tabs:

#73 chore/bindings: update safe_app and safe_authenticator bindings to v0.9.1
  CakeHelperScripts/NativeScriptDownloader.cake
Labels: Binding, Don't Merge !!!

#74 Test package reference
  .gitignore
  SafeApp.MockAuthBindings.Android/SafeApp.MockAuthBindings.Android.csproj
  SafeApp.MockAuthBindings.Android/packages.config
  SafeApp.MockAuthBindings.iOS/SafeApp.MockAuthBindings.iOS.csproj
  SafeApp.MockAuthBindings.iOS/packages.config
  SafeApp.Tests.Android/Properties/AndroidManifest.xml
  SafeApp.Tests.Android/SafeApp.Tests.Android.csproj
  SafeApp.Tests.Android/app.config
  SafeApp.Tests.Android/packages.config
  SafeApp.Tests.Framework/SafeApp.Tests.Framework.csproj
  SafeApp.Tests.Framework/packages.config
  SafeApp.Tests.iOS/SafeApp.Tests.iOS.csproj
  SafeApp.Tests.iOS/packages.config
Labels: e/M :clock3:
